### ISSUE TITLE
Connect to other Clouds or other Clouds Device Managment services?

### ISSUE THREAD

**Issue by 0Grit** [ARMmbed/connector-bridge#2]
@DougAnsonAtARM 
Is this written specifically to bridge device management services of other cloud providers?
Or can it be used to say... forward Pelion device data into a database hosted by another cloud provider?

**Comment by DougAnsonAustinTX** [comment]
it's mostly used when you wish to utilize/interact with a device "twin" in the other cloud... if you wish to only cache all device telemetry for later analysis then easier approaches exist...

Doug

**Comment by 0Grit** [comment]
I assume the bridges are purely for migration scenarios then?

**Comment by DougAnsonAustinTX** [comment]
not necessarily.... it can definitely be used to create durable twins.... ones that will be compatible with native apps in the selected cloud...

Doug

**Comment by 0Grit** [comment]
I suppose the cost of both DM services + running the bridge might be worth it to those who want to transparently enable what IoT Hub lacks.
